name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Aggiorna ogni 24 ore
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: TryHackMe Update Badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "gssab3"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
